### Operaciones aritméticas

##### Las operaciones se aplican cuando coinciden los índices en ambas estructuras(series , dataframe).
##### Si coinciden los índices rellenacon NaN.
##### Pandas tiene varias funciones básicas que permiten establecer un valor de relleno
##### En un numpy, los arrays deben tener las mismas dimensiones para realizar las operaciones

In [1]:
import numpy as np
import pandas as pd

##### Sumamos dos series donde coinciden los índices

In [2]:
serie1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
serie2 = pd.Series([10, 11, 12], index=['a', 'b', 'c'])
serie1+serie2

a    11
b    13
c    15
dtype: int64

##### Ahora sumamos dos series donde no coinciden los índices

In [3]:
serie1 = pd.Series([0, 1, 2, 3,], index=['a', 'b', 'k', 'l'])
serie2 = pd.Series([10, 11, 12, 13, 14, 15, 16], index=['a', 'b', 'c', 'd', 'f', 'g', 'h'])
serie1+serie2

a    10.0
b    12.0
c     NaN
d     NaN
f     NaN
g     NaN
h     NaN
k     NaN
l     NaN
dtype: float64

##### Ejemplos con Dataframe

In [6]:
lista_pares = [x for x in range(10) if x % 2 == 0]
lista_impares = [x for x in range(10) if x % 2 != 0]
print(lista_pares)
print(lista_impares)

[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]

In [9]:
pares_df = pd.DataFrame(index=['a', 'b', 'c', 'd', 'e'])
impares_df = pd.DataFrame(index=['a', 'b', 'c', 'd', 'f'])
pares_df["val"] = lista_pares
impares_df["val"] = lista_impares
print("Pares:\n", pares_df)
print("Impares:\n", impares_df)

Pares:
    val
a    0
b    2
c    4
d    6
e    8
Impares:
    val
a    1
b    3
c    5
d    7
f    9

##### Sumamos los dos dataframe

In [21]:
pares_df.add(impares_df)

    val
a   1.0
b   5.0
c   9.0
d  13.0
e   NaN
f   NaN

##### Ahora los sumamos, pero dando un valor a los nulos

In [20]:
pares_df.add(impares_df, fill_value=0)

    val
a   1.0
b   5.0
c   9.0
d  13.0
e   8.0
f   9.0

##### Ahora los multiplicamos

In [15]:
pares_df.mul(impares_df, fill_value=0)

    val
a   0.0
b   6.0
c  20.0
d  42.0
e   0.0
f   0.0

In [32]:
data1 = pd.DataFrame([10, 20, 30], index=['a', 'b', 'c'])
data2 = pd.DataFrame([5, 10, 15], index=['a', 'b', 'c'])
print("data1:\n", data1)
print("data2:\n", data2)

data1:
     0
a  10
b  20
c  30
data2:
     0
a   5
b  10
c  15

##### Aquí la diferencia entre div y rdiv

In [26]:
data1.div(data2)

     0
a  2.0
b  2.0
c  2.0

In [27]:
data1.rdiv(data2)

     0
a  0.5
b  0.5
c  0.5

##### Diferencia entre sub y rsub

In [28]:
data1.sub(data2)

    0
a   5
b  10
c  15

In [29]:
data1.rsub(data2)

    0
a  -5
b -10
c -15